from datetime import date, timedelta
from .database import engine, Base, SessionLocal
from .models import Customer

customer_payload = [
    # Explicit test customers required for demos and verification
    {
        "customer_id": "C001",
        "name": "Test Approved",
        "email": "test.approved@example.com",
        "purchase_date": date.today() - timedelta(days=5),
        "delivery_date": date.today() - timedelta(days=2),
        "product_name": "Sample Widget",
        "product_type": "electronics",
        "order_value": 49.99,
        "refund_count": 0,
        "loyalty_status": "standard",
        "fraud_score": 5,
        "country": "United States",
    },
    {
        "customer_id": "C010",
        "name": "Test Denied",
        "email": "test.denied@example.com",
        "purchase_date": date.today() - timedelta(days=60),
        "delivery_date": date.today() - timedelta(days=55),
        "product_name": "Old Item",
        "product_type": "apparel",
        "order_value": 29.99,
        "refund_count": 0,
        "loyalty_status": "standard",
        "fraud_score": 8,
        "country": "United States",
    },
    {
        "customer_id": "C015",
        "name": "Test Fraud",
        "email": "test.fraud@example.com",
        "purchase_date": date.today() - timedelta(days=3),
        "delivery_date": date.today() - timedelta(days=1),
        "product_name": "Premium Gadget",
        "product_type": "electronics",
        "order_value": 199.0,
        "refund_count": 0,
        "loyalty_status": "standard",
        "fraud_score": 95,
        "country": "United States",
    },
    {
        "customer_id": "CUST001",
        "name": "Amelia Rivera",
        "email": "amelia.rivera@example.com",
        "purchase_date": date.today() - timedelta(days=15),
        "delivery_date": date.today() - timedelta(days=10),
        "product_name": "Crystal Echo Bluetooth Speaker",
        "product_type": "electronics",
        "order_value": 129.99,
        "refund_count": 0,
        "loyalty_status": "standard",
        "fraud_score": 12,
        "country": "United States",
    },
    {
        "customer_id": "CUST002",
        "name": "David Chen",
        "email": "david.chen@example.com",
        "purchase_date": date.today() - timedelta(days=60),
        "delivery_date": date.today() - timedelta(days=55),
        "product_name": "Urban Trail Running Shoes",
        "product_type": "apparel",
        "order_value": 89.95,
        "refund_count": 1,
        "loyalty_status": "standard",
        "fraud_score": 11,
        "country": "Canada",
    },
    {
        "customer_id": "CUST003",
        "name": "Priya Nair",
        "email": "priya.nair@example.com",
        "purchase_date": date.today() - timedelta(days=20),
        "delivery_date": date.today() - timedelta(days=18),
        "product_name": "GlamourSkin Foundation Kit",
        "product_type": "beauty",
        "order_value": 42.50,
        "refund_count": 0,
        "loyalty_status": "premium",
        "fraud_score": 7,
        "country": "India",
    },
    {
        "customer_id": "CUST004",
        "name": "Marcus Silva",
        "email": "marcus.silva@example.com",
        "purchase_date": date.today() - timedelta(days=8),
        "delivery_date": date.today() - timedelta(days=2),
        "product_name": "AeroFit Backpack",
        "product_type": "accessories",
        "order_value": 68.00,
        "refund_count": 2,
        "loyalty_status": "premium",
        "fraud_score": 23,
        "country": "Brazil",
    },
    {
        "customer_id": "CUST005",
        "name": "Olivia Martin",
        "email": "olivia.martin@example.com",
        "purchase_date": date.today() - timedelta(days=3),
        "delivery_date": date.today() - timedelta(days=1),
        "product_name": "Virtual Design Course Access",
        "product_type": "digital",
        "order_value": 199.00,
        "refund_count": 0,
        "loyalty_status": "standard",
        "fraud_score": 10,
        "country": "United Kingdom",
    },
    {
        "customer_id": "CUST006",
        "name": "Liam O'Connor",
        "email": "liam.oconnor@example.com",
        "purchase_date": date.today() - timedelta(days=22),
        "delivery_date": date.today() - timedelta(days=19),
        "product_name": "Premium Leather Wallet",
        "product_type": "accessories",
        "order_value": 54.99,
        "refund_count": 4,
        "loyalty_status": "standard",
        "fraud_score": 34,
        "country": "Ireland",
    },
    {
        "customer_id": "CUST007",
        "name": "Nina Kovács",
        "email": "nina.kovacs@example.com",
        "purchase_date": date.today() - timedelta(days=31),
        "delivery_date": date.today() - timedelta(days=29),
        "product_name": "HomeSmart Coffee Machine",
        "product_type": "home",
        "order_value": 239.95,
        "refund_count": 0,
        "loyalty_status": "premium",
        "fraud_score": 18,
        "country": "Hungary",
    },
    {
        "customer_id": "CUST008",
        "name": "Jamal Thompson",
        "email": "jamal.thompson@example.com",
        "purchase_date": date.today() - timedelta(days=12),
        "delivery_date": date.today() - timedelta(days=6),
        "product_name": "RainGuard Jacket",
        "product_type": "apparel",
        "order_value": 110.00,
        "refund_count": 0,
        "loyalty_status": "standard",
        "fraud_score": 95,
        "country": "South Africa",
    },
    {
        "customer_id": "CUST009",
        "name": "Sofia Hernandez",
        "email": "sofia.hernandez@example.com",
        "purchase_date": date.today() - timedelta(days=25),
        "delivery_date": date.today() - timedelta(days=22),
        "product_name": "Gourmet Chef Knife",
        "product_type": "kitchen",
        "order_value": 74.99,
        "refund_count": 1,
        "loyalty_status": "standard",
        "fraud_score": 15,
        "country": "Mexico",
    },
    {
        "customer_id": "CUST010",
        "name": "Hana Kim",
        "email": "hana.kim@example.com",
        "purchase_date": date.today() - timedelta(days=29),
        "delivery_date": date.today() - timedelta(days=28),
        "product_name": "Portable Yoga Mat",
        "product_type": "fitness",
        "order_value": 39.99,
        "refund_count": 0,
        "loyalty_status": "premium",
        "fraud_score": 9,
        "country": "South Korea",
    },
    {
        "customer_id": "CUST011",
        "name": "Ethan Brooks",
        "email": "ethan.brooks@example.com",
        "purchase_date": date.today() - timedelta(days=38),
        "delivery_date": date.today() - timedelta(days=35),
        "product_name": "Glowing Gaming Mouse",
        "product_type": "electronics",
        "order_value": 59.99,
        "refund_count": 0,
        "loyalty_status": "standard",
        "fraud_score": 4,
        "country": "Australia",
    },
    {
        "customer_id": "CUST012",
        "name": "Maya Patel",
        "email": "maya.patel@example.com",
        "purchase_date": date.today() - timedelta(days=45),
        "delivery_date": date.today() - timedelta(days=40),
        "product_name": "Child Safety Car Seat",
        "product_type": "baby",
        "order_value": 189.99,
        "refund_count": 2,
        "loyalty_status": "standard",
        "fraud_score": 27,
        "country": "United States",
    },
    {
        "customer_id": "CUST013",
        "name": "Aleksandr Petrov",
        "email": "aleksandr.petrov@example.com",
        "purchase_date": date.today() - timedelta(days=3),
        "delivery_date": date.today() - timedelta(days=1),
        "product_name": "EdgeShield Protective Screen",
        "product_type": "electronics",
        "order_value": 39.99,
        "refund_count": 0,
        "loyalty_status": "premium",
        "fraud_score": 14,
        "country": "Russia",
    },
    {
        "customer_id": "CUST014",
        "name": "Sara Nascimento",
        "email": "sara.nascimento@example.com",
        "purchase_date": date.today() - timedelta(days=59),
        "delivery_date": date.today() - timedelta(days=56),
        "product_name": "Advanced Sleep Headphones",
        "product_type": "electronics",
        "order_value": 85.00,
        "refund_count": 0,
        "loyalty_status": "premium",
        "fraud_score": 32,
        "country": "Portugal",
    },
    {
        "customer_id": "CUST015",
        "name": "Noah Kim",
        "email": "noah.kim@example.com",
        "purchase_date": date.today() - timedelta(days=27),
        "delivery_date": date.today() - timedelta(days=25),
        "product_name": "Luxury Watch Band",
        "product_type": "accessories",
        "order_value": 79.00,
        "refund_count": 3,
        "loyalty_status": "standard",
        "fraud_score": 49,
        "country": "United States",
    },
]


def seed_database() -> int:
    Base.metadata.drop_all(bind=engine)
    Base.metadata.create_all(bind=engine)
    session = SessionLocal()
    try:
        for item in customer_payload:
            customer = Customer(**item)
            session.add(customer)
        session.commit()
        return len(customer_payload)
    finally:
        session.close()

if __name__ == "__main__":
    total = seed_database()
    print(f"Seeded {total} customer profiles.")
